### ISSUE TITLE
support for data_files kwarg

### ISSUE THREAD

**Issue by graingert-coef** [asottile/setup-py-upgrade#147]
input:
```
setup(
      name="example",
      data_files=[('bitmaps', ['bm/b1.gif', 'bm/b2.gif']),
                  ('config', ['cfg/data.cfg'])],
     )
```

output:

```
Traceback (most recent call last):
  File "/Users/thomas/.local/pipx/.cache/f253ae1f378f350/bin/setup-py-upgrade", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/thomas/.local/pipx/.cache/f253ae1f378f350/lib/python3.12/site-packages/setup_py_upgrade.py", line 186, in main
    sections = {k: _reformat(v) for k, v in visitor.sections.items() if v}
                   ^^^^^^^^^^^^
  File "/Users/thomas/.local/pipx/.cache/f253ae1f378f350/lib/python3.12/site-packages/setup_py_upgrade.py", line 154, in _reformat
    new_section[key] = _list_as_str(value)
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/thomas/.local/pipx/.cache/f253ae1f378f350/lib/python3.12/site-packages/setup_py_upgrade.py", line 143, in _list_as_str
    return '\n' + '\n'.join(lst)
                  ^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, tuple found
```

data_files is deprecated though - might be nicer to get a different exception though

**Comment by asottile** [comment]
the docs say it's supposed to be a list of strings so I think this might be garbage in garbage out?

**Comment by graingert-coef** [comment]
@asottile this is from the example here: https://setuptools.pypa.io/en/latest/deprecated/distutils/setupscript.html#installing-additional-files

**Comment by graingert-coef** [comment]
@asottile I got the docs updated on the setuptools side: https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-data-files
