### ISSUE TITLE
Multiple failures on running the package

### ISSUE THREAD

**Issue by suryasr007** [asottile/setup-py-upgrade#7]
Hi

When try run the `setup-py-upgrade ../flake8`. I am getting following errors`

``` bash
→ setup-py-upgrade ../flake8
Traceback (most recent call last):
  File "/home/surya/py_venvs/flake8/lib/python3.7/site-packages/setup_py_upgrade.py", line 121, in visit_Call
    value = ast.literal_eval(kwd.value)
  File "/usr/lib/python3.7/ast.py", line 91, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python3.7/ast.py", line 90, in _convert
    return _convert_signed_num(node)
  File "/usr/lib/python3.7/ast.py", line 63, in _convert_signed_num
    return _convert_num(node)
  File "/usr/lib/python3.7/ast.py", line 55, in _convert_num
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Attribute object at 0x7f8acddfd358>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/surya/py_venvs/flake8/bin/setup-py-upgrade", line 10, in <module>
    sys.exit(main())
  File "/home/surya/py_venvs/flake8/lib/python3.7/site-packages/setup_py_upgrade.py", line 154, in main
    visitor.visit(tree)
  File "/usr/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/usr/lib/python3.7/ast.py", line 270, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/usr/lib/python3.7/ast.py", line 272, in generic_visit
    self.visit(value)
  File "/usr/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/home/surya/py_venvs/flake8/lib/python3.7/site-packages/setup_py_upgrade.py", line 123, in visit_Call
    raise NotImplementedError(f'unparsable {kwd.arg}')
NotImplementedError: unparsable version
```

OS: **Ubuntu 19.04**
Python: **3.7**

**Comment by asottile** [comment]
Anything which isn't statically computable cannot be converted automatically.

The workaround is to temporarily remove that key, run it, and then put it back (or figure out a way to convert it to static manually before running).
