### ISSUE TITLE
Doesn't support variables for metadata values in setup.py

### ISSUE THREAD

**Issue by jmao-denver** [asottile/setup-py-upgrade#74]
This is a simplified version of the setup.py used for our Python package. We'd like to move to the declarative metadata based packaging approach. I tried this tool after watching Anthony's Youtube video on this very topic. The problem I ran into seems minor but I don't have the capacity to debug it at the moment.

```
#
#  Copyright (c) 2016-2021 Deephaven Data Labs and Patent Pending
#
import os
import pathlib
from setuptools.extern import packaging
from setuptools import find_packages, setup

dh_version = os.environ['DEEPHAVEN_VERSION']

setup(name='deephaven',
      version=dh_version,
      packages=find_packages(exclude=("tests",)),
      url='https://deephaven.io/',
      author='Deephaven Data Labs',
      author_email='python@deephaven.io',
      license='Deephaven Community License',
      test_loader='unittest:TestLoader',
      classifiers=[
          'Development Status :: 2 - Pre-Alpha',
          'Intended Audience :: Developers, Data Scientists',
          'Topic :: Software Development :: Build Tools',
          'License :: Other/Proprietary License',
          'Programming Language :: Python :: 3.7',
      ],
      keywords='Deephaven Development'
      )
```
will except out:
```
/tmp setup-py-upgrade .
Traceback (most recent call last):
  File "/Users/jianfengmao/.pyenv/versions/3.7.10/lib/python3.7/site-packages/setup_py_upgrade.py", line 126, in visit_Call
    value = ast.literal_eval(kwd.value)
  File "/Users/jianfengmao/.pyenv/versions/3.7.10/lib/python3.7/ast.py", line 91, in literal_eval
    return _convert(node_or_string)
  File "/Users/jianfengmao/.pyenv/versions/3.7.10/lib/python3.7/ast.py", line 90, in _convert
    return _convert_signed_num(node)
  File "/Users/jianfengmao/.pyenv/versions/3.7.10/lib/python3.7/ast.py", line 63, in _convert_signed_num
    return _convert_num(node)
  File "/Users/jianfengmao/.pyenv/versions/3.7.10/lib/python3.7/ast.py", line 55, in _convert_num
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Name object at 0x10505c1d0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jianfengmao/.pyenv/versions/3.7.10/bin/setup-py-upgrade", line 8, in <module>
    sys.exit(main())
  File "/Users/jianfengmao/.pyenv/versions/3.7.10/lib/python3.7/site-packages/setup_py_upgrade.py", line 168, in main
    visitor.visit(tree)
  File "/Users/jianfengmao/.pyenv/versions/3.7.10/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/Users/jianfengmao/.pyenv/versions/3.7.10/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/Users/jianfengmao/.pyenv/versions/3.7.10/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/Users/jianfengmao/.pyenv/versions/3.7.10/lib/python3.7/ast.py", line 281, in generic_visit
    self.visit(value)
  File "/Users/jianfengmao/.pyenv/versions/3.7.10/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/Users/jianfengmao/.pyenv/versions/3.7.10/lib/python3.7/site-packages/setup_py_upgrade.py", line 128, in visit_Call
    raise NotImplementedError(f'unparsable: {kwd.arg}=')
NotImplementedError: unparsable: version=
```

**Comment by asottile** [comment]
intentionally, what you're asking it to do is impossible

**Comment by asottile** [comment]
see also #7 #16

**Comment by jmao-denver** [comment]
thanks, should have searched in the closed issues first 😄
