### ISSUE TITLE
Consider adding support for `extras_require`

### ISSUE THREAD

**Issue by Harmouch101** [asottile/setup-py-upgrade#76]
This project is kinda cool. Unfortunately, the current version doesn't support the `extras_require` section. Apparently, the most extreme case is [ethereum/web3.py#2355](https://github.com/ethereum/web3.py/pull/2355/files) where `dev` depends upon previously defined directives(`tester`, `linter`, `docs`).

Syntax for `extras_require` is documented [here](https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html?highlight=options.extras_require#configuring-setup-using-setup-cfg-files).

**Comment by asottile** [comment]
works fine for me:

```python
from setuptools import setup

setup(
    name='wat',
    extras_require={
        'foo': ['cfgv'],
        'bar': ['astpretty', 'pyupgrade'],
    },
)
```

```console
$ setup-py-upgrade .
./setup.py and ./setup.cfg written!
```

```ini
[metadata]
name = wat

[options.extras_require]
foo = cfgv
bar =
    astpretty
    pyupgrade
```

**Comment by Harmouch101** [comment]
@asottile Ummm, you are right. However, it doesn't support explicitly changing this section. Take the following as an example:

```python3
from setuptools import setup

extra_requires = {
        'foo': ['cfgv'],
        'bar': ['astpretty', 'pyupgrade'],
}

extra_requires['bar'] += extra_requires[bar]

setup(
    name='wat',
    extras_require=extra_requires,
)
```

```sh
$ setup-py-upgrade .

Traceback (most recent call last):
  File "/home/harmouch/Desktop/python_files/linux-cli-project/pylinux_cli/pylinux_cli/.venv/bin/setup-py-upgrade", line 8, in <module>
    sys.exit(main())
  File "/home/harmouch/Desktop/python_files/linux-cli-project/pylinux_cli/pylinux_cli/.venv/lib/python3.8/site-packages/setup_py_upgrade.py", line 168, in main
    visitor.visit(tree)
  File "/usr/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/usr/lib/python3.8/ast.py", line 379, in generic_visit
    self.visit(item)
  File "/usr/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/usr/lib/python3.8/ast.py", line 381, in generic_visit
    self.visit(value)
  File "/usr/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/home/harmouch/Desktop/python_files/linux-cli-project/pylinux_cli/pylinux_cli/.venv/lib/python3.8/site-packages/setup_py_upgrade.py", line 128, in visit_Call
    raise NotImplementedError(f'unparsable: {kwd.arg}=')
NotImplementedError: unparsable: extras_require=
```

**Comment by asottile** [comment]
yeah it cannot solve the halting problem -- your code needs to be identifiable statically

**Comment by Harmouch101** [comment]
Got it! I think It would be great to add support for this dynamic case.

**Comment by asottile** [comment]
the halting problem is unsolvable

**Comment by Harmouch101** [comment]
... by any Turing machine. However, I think we, as human species, are not able to determine whether or not a given Turing machine will halt...
